---
version: "2"

linters:
  default: standard
  enable:
    - misspell
    - revive
  exclusions:
    rules:
      - linters:
          - revive
        text: "^exported:"
    paths:
      - internal/congestion/bbr
      - internal/congestion/brutal
      - internal/congestion/common

formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    paths:
      - internal/congestion/bbr
      - internal/congestion/brutal
      - internal/congestion/common
